name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]

    rabbitmq:
      image: rabbitmq
      env:
        RABBITMQ_DEFAULT_USER: craiga
        RABBITMQ_DEFAULT_PASS: security_is_important
      ports:
        - 5672:5672

    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bootstrap
      - run: npm run test
        env:
          RABBITMQ_URL: amqp://localhost:${{ job.services.rabbitmq.ports[5672] }}


  build-windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run bootstrap
      - run: npm run test
